# Browser test of the AI path against a fake OpenAI-compatible server (no network needed).
import subprocess, time, urllib.request
from playwright.sync_api import sync_playwright
fake = subprocess.Popen(["node", "tests/fake-llm.mjs"])
env = {"PORT": "3457", "PATH": "/usr/bin:/usr/local/bin:/bin", "LLM_BASE_URL": "http://localhost:4999", "LLM_API_KEY": "test", "LLM_MODELS": "m1,m2"}
srv = subprocess.Popen(["node", "server.mjs"], env=env)
time.sleep(1.2)
BASE = "http://localhost:3457"
def setmode(m): urllib.request.urlopen(urllib.request.Request("http://localhost:4999/mode", data=m.encode(), method="POST")).read()
problems = []
def check(c, m):
    print(("PASS " if c else "FAIL ") + m)
    if not c: problems.append(m)
try:
    with sync_playwright() as p:
        b = p.chromium.launch(); ctx = b.new_context(viewport={"width": 1400, "height": 900})
        ctx.route("**/fonts.g*/**", lambda r: r.abort())
        pg = ctx.new_page(); errors = []; dialogs = []
        pg.on("pageerror", lambda e: errors.append(str(e)))
        pg.on("dialog", lambda d: (dialogs.append(d.message), d.dismiss()))
        pg.goto(BASE); pg.wait_for_timeout(800)
        check("AI" in pg.text_content("#ai-status"), "status shows AI: " + pg.text_content("#ai-status"))
        pg.fill("#f-desc", "Earbuds for gym bros, funny reels")
        pg.locator("#plan-best").click()
        pg.wait_for_function("document.querySelector('#board') && document.querySelector('#board').textContent.includes('AI line')", timeout=15000)
        check(True, "auto-polish applied AI lines")
        check("AI hook one" in pg.text_content("#board .hooks"), "AI hooks applied")
        pg.wait_for_timeout(300)
        check(pg.locator("#board [data-act=ai-scene]").count() > 0, "Rewrite with AI buttons visible")
        def say(msg):
            n = pg.locator("#dir-log .msg.bot:not(.typing)").count()
            pg.fill("#dir-input", msg); pg.press("#dir-input", "Enter")
            pg.wait_for_function(f"document.querySelectorAll('#dir-log .msg.bot:not(.typing)').length > {n}", timeout=30000)
            pg.wait_for_timeout(200)
            return pg.locator("#dir-log .msg.bot:not(.typing)").last.text_content()
        r = say("make scene 2 warmer and more personal")
        check("warmer" in r and "AI rewrote this warmly" in pg.text_content("#board"), f"AI creative edit applied: {r!r}")
        r = say("cut it to 15 seconds")
        check("15" in r, f"structural edit stays local: {r!r}")
        pg.locator("#board [data-act=ai-scene]").first.click(); pg.wait_for_timeout(1500)
        check(not errors, "rewrite-with-AI button ok")
        setmode("evil")
        r = say("make scene 1 punchier")
        pg.wait_for_timeout(300)
        check(pg.locator("#board img, #dir-log img, #board script, #dir-log script").count() == 0 and not dialogs, f"malicious AI output neutralised: {r!r}")
        check("undefined" not in pg.text_content("#board"), "board intact after evil ops")
        setmode("garbage")
        r = say("make scene 2 more emotional")
        check(bool(r.strip()), f"garbage AI output falls back: {r!r}")
        setmode("429")
        r = say("make scene 2 funnier")
        check(bool(r.strip()), f"rate limit falls back: {r!r}")
        setmode("ok")
        pg.locator("#help-fab").click()
        pg.fill("#help-input", "do you integrate with shopify"); pg.press("#help-input", "Enter")
        pg.wait_for_function("[...document.querySelectorAll('#help-log .msg.bot')].some(m => m.textContent.includes('AI says'))", timeout=15000)
        check(True, "help bot uses AI when available")
        setmode("slow")
        t0 = time.time()
        n = pg.locator("#help-log .msg.bot:not(.typing)").count()
        pg.fill("#help-input", "who founded the company"); pg.press("#help-input", "Enter")
        pg.wait_for_function(f"document.querySelectorAll('#help-log .msg.bot:not(.typing)').length > {n}", timeout=40000)
        dt = time.time() - t0
        r = pg.locator("#help-log .msg.bot:not(.typing)").last.text_content()
        check(dt < 13 and "contact" in r.lower(), f"slow AI -> help still answers in {dt:.1f}s: {r[:70]!r}")
        setmode("401")
        n = pg.locator("#help-log .msg.bot:not(.typing)").count()
        pg.fill("#help-input", "what is your office address"); pg.press("#help-input", "Enter")
        pg.wait_for_function(f"document.querySelectorAll('#help-log .msg.bot:not(.typing)').length > {n}", timeout=20000)
        r = pg.locator("#help-log .msg.bot:not(.typing)").last.text_content()
        check("contact" in r.lower(), f"bad key falls back: {r[:60]!r}")
        check("Built-in" in pg.text_content("#ai-status"), "badge switches to built-in after bad key")
        calls_before = urllib.request.urlopen("http://localhost:4999/calls").read()
        pg.locator("#help-close").click()
        r = say("make scene 2 more emotional")
        calls_after = urllib.request.urlopen("http://localhost:4999/calls").read()
        check(calls_before == calls_after and bool(r.strip()), f"after bad key, app stops calling AI: {r[:60]!r}")
        pg.screenshot(path="tests/screenshots/07-ai.png", full_page=True)
        check(not errors, "no JS errors: " + "; ".join(errors[:3]))
        b.close()
finally:
    srv.terminate(); fake.terminate()
print("PROBLEMS:", len(problems)); [print(" -", x) for x in problems]
